### ISSUE TITLE
Apply bootstrap classes

### ISSUE THREAD

**Issue by ChaudhryAtif** [rhostem/ng2-simple-autocomplete#3]
Is it possible to apply bootstrap classes to the input? For example, "form-control" or "form-control form-control-sm"?

If so, can you provide an example.

Thanks

**Comment by rhostem** [comment]
I didn't implemented attaching external classes for component. Overwriting component style by `[ngStyle]` and `style` input property is written in below lines of source. 

https://github.com/rhostem/ng2-simple-autocomplete/blob/master/src/ng2-simple-autocomplete/index.ts#L45
https://github.com/rhostem/ng2-simple-autocomplete/blob/master/src/ng2-simple-autocomplete/index.ts#L63
https://github.com/rhostem/ng2-simple-autocomplete/blob/master/src/ng2-simple-autocomplete/index.ts#L103
https://github.com/rhostem/ng2-simple-autocomplete/blob/master/src/ng2-simple-autocomplete/index.ts#L123

**Comment by ChaudhryAtif** [comment]
@rhostem #4 please see PR. I think this should allow for custom classes to be applied to the input. Then the result section should be able to be modified via component styles.
