### ISSUE TITLE
Unexpected value 'Ng2SimpleAutocomplete' declared by the module

### ISSUE THREAD

**Issue by balaganapathynt** [rhostem/ng2-simple-autocomplete#6]
Getting below error from console
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Unexpected value 'Ng2SimpleAutocomplete' declared by the module 'VendorsModule'. Please add a @Pipe/@Directive/@Component annotation.
Error: Unexpected value 'Ng2SimpleAutocomplete' declared by the module 'VendorsModule'. Please add a @Pipe/@Directive/@Component annotation

**Comment by rhostem** [comment]
If you use latest version of Angular and CLI, some problem would be happen. This component was developed with webpack, not Angualr CLI, so there is several problems I didn't catch. Unfortunately I don't have a plan to update this component for now. Sorry.
